'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ToDoList

    '''<summary>
    '''ErrorLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TaskName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TaskName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ErrorLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Owner1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Owner1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DueDate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DueDate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ErrorLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Account1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Account1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OverrideRate1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OverrideRate1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Description1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Description1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Add1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Add1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Search1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Search1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Clear1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Clear1 As Global.System.Web.UI.WebControls.Button
End Class
